  language: node_js
  node_js:
  - 6.*
  before_install:
  - chmod a+x ./scripts/test
  - npm install -g dredd
  script: ./scripts/test
  notifications:
    email:
      recipients:
        - brendon@foreup.com
      on_success: change # default: change
      on_failure: always # default: always
